# Generated by Django 4.2.3 on 2023-11-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_orders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
    ]
